defaults:
  - _self_

experiment:
  gc_user: erikaa
  wandb:
    entity: graphcore
    project: post-training-frameworks
    run_name: ${..gc_user}-nemo-grpo_smoke-1node_4gpu
    dir: ${experiment.dir}/wandb

resource:
  num_nodes: 1
  gpus_per_node: 4
  cpus_per_gpu: 20
  omp_num_threads: ${.cpus_per_gpu}
  memory_per_cpu: 4
  cpus_per_node: 20
  kube_job_name: null
