defaults:
  - _self_

experiment:
  gc_user: erikaa
  wandb:
    run_name: ${..gc_user}-nemo-grpo-smoke

resource:
  num_nodes: 1
  gpus_per_node: 1
  cpus_per_gpu: 20
  omp_num_threads: ${.cpus_per_gpu}
  memory_per_cpu: 4
  cpus_per_node: 20
  kube_job_name: null
